"""Const for LIFX Virtual Lights."""

DOMAIN = "lifx_virtual_lights"
CONF_NAME = "name"
CONF_TARGET_LIGHT = "target_light"
CONF_ZONE_START = "zone_start"
CONF_ZONE_END = "zone_end"
CONF_TURN_ON_BRIGHTNESS = "turn_on_brightness"
CONF_TURN_ON_DURATION = "turn_on_duration"
CONF_TURN_OFF_DURATION = "turn_off_duration"
